name: navalistview
description: "A simple infinitely scrollable list view made for Navatech AI as
  part of the ongoing hiring process for the role Lead Flutter Developer"

publish_to: 'none'

version: 1.0.0+1
isar_version: &isar_version 3.0.2

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  fluttertoast: ^8.2.8
  http: ^1.2.2
  isar: 3.0.2
  isar_flutter_libs: 3.0.2
  json_annotation: ^4.9.0
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  isar_generator: 3.0.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
